// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqiMCdSxS2QYBXFR1l9y8h7wQGGAPefI8',
    appId: '1:619682100868:web:eb9b23a0ba59e93f09f4d1',
    messagingSenderId: '619682100868',
    projectId: 'flutterteamproject-19374',
    authDomain: 'flutterteamproject-19374.firebaseapp.com',
    storageBucket: 'flutterteamproject-19374.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0rGayQvQBRX7xHSZKGQG-O2hjo6mzVdM',
    appId: '1:619682100868:android:ea57f55c685f482809f4d1',
    messagingSenderId: '619682100868',
    projectId: 'flutterteamproject-19374',
    storageBucket: 'flutterteamproject-19374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVNE43mcfYSpRYuGUxF03K4DO6bYvPoU',
    appId: '1:619682100868:ios:8a3714fcfd7d815709f4d1',
    messagingSenderId: '619682100868',
    projectId: 'flutterteamproject-19374',
    storageBucket: 'flutterteamproject-19374.firebasestorage.app',
    iosBundleId: 'com.example.teamProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGVNE43mcfYSpRYuGUxF03K4DO6bYvPoU',
    appId: '1:619682100868:ios:8a3714fcfd7d815709f4d1',
    messagingSenderId: '619682100868',
    projectId: 'flutterteamproject-19374',
    storageBucket: 'flutterteamproject-19374.firebasestorage.app',
    iosBundleId: 'com.example.teamProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqiMCdSxS2QYBXFR1l9y8h7wQGGAPefI8',
    appId: '1:619682100868:web:d18a43e82542441d09f4d1',
    messagingSenderId: '619682100868',
    projectId: 'flutterteamproject-19374',
    authDomain: 'flutterteamproject-19374.firebaseapp.com',
    storageBucket: 'flutterteamproject-19374.firebasestorage.app',
  );

}